version: 0.0
os: linux
files:
  - source: /
    destination: /opt/race-result-api
    overwrite: yes
permissions:
  - object: /opt/race-result-api
    owner: ubuntu
    group: ubuntu
  - object: /opt/race-result-api/scripts
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ubuntu