version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Build started on `date`
      - export HOME=/root
      - chmod +x mvnw
  build:
    commands:
      - echo Building the Maven project...
      - echo "Java version:"
      - java -version
      - echo "Maven wrapper version:"
      - ./mvnw --version
      - ./mvnw clean package -DskipTests
      - echo Build completed on `date`

artifacts:
  files:
    - target/*.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'