version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started on `date`
      - chmod +x mvnw
  build:
    commands:
      - echo Building the Maven project...
      - ./mvnw clean package
      - echo Build completed on `date`

artifacts:
  files:
    - target/*.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'